version: "3.4"

services:
  thoth-duplicity:
    build: .
    # image: unixorn/thoth-duplicity
    environment:
      DEBUG: ${DEBUG:-}
      BACKUP_LOCATION: ${BACKUP_LOCATION:-}
      BACKUP_REPOSITORY: ${BACKUP_REPOSITORY:-}
      B2_ACCOUNT_ID: $B2_ACCOUNT_ID
      B2_ACCOUNT_KEY: $B2_ACCOUNT_KEY
      RESTIC_PASSWORD: $RESTIC_PASSWORD
      HOSTNAME: ${RESTIC_HOSTNAME:-$HOSTNAME}
      KEEP_LAST: ${KEEP_LAST:-2}
      KEEP_HOURS: ${KEEP_HOURS:-24}
      KEEP_DAYS: ${KEEP_DAYS:-7}
      KEEP_WEEKS: ${KEEP_WEEKS:-4}
      KEEP_MONTHS: ${KEEP_MONTHS:-3}
      KEEP_YEARS: ${KEEP_YEARS:-1}
    volumes:
      - "/Users/jblock/Dropbox:/data"
      - "./scripts:/scripts"
      - "./rootcache:/root/.cache"
