#!/usr/bin/env bash
#
# Copy duplicacy and duplicacy-util from the github releases pages of
# the projects. This makes multi-architecture container image builds
# much faster.
#
# Copyright 2019, Joe Block <jpb@unixorn.net>

set -o pipefail
set -o errexit

ARCH=$(uname -m)
DUPLICACY_VERSION=${DUPLICACY_VERSION:-2.2.3}
DUPLICACY_UTIL_VERSION=${DUPLICACY_UTIL_VERSION:-1.5}

case "$ARCH" in
  x86_64 )
    duplicacy_binary_arch='linux_x64'
    util_arch='linux_x64'
    ;;
  aarch64 )
    duplicacy_binary_arch='linux_arm64'
    util_arch='linux_arm'
    ;;
  armv7l )
    duplicacy_binary_arch='linux_arm'
    util_arch='linux_arm'
    ;;
  * )
    echo "Sorry, don't know how to handle architecture $ARCH"
    exit 1
    ;;
esac

DUPLICACY_URL="https://github.com/gilbertchen/duplicacy/releases/download/v${DUPLICACY_VERSION}/duplicacy_${duplicacy_binary_arch}_${DUPLICACY_VERSION}"
UTIL_URL="https://github.com/jeffaco/duplicacy-util/releases/download/v${DUPLICACY_UTIL_VERSION}/duplicacy-util_${util_arch}_${DUPLICACY_UTIL_VERSION}"

if [[ -n "$DEBUG_F" ]]; then
  echo "DUPLICACY_VERSION: $DUPLICACY_VERSION" >> "${DEBUG_F}"
  echo "DUPLICACY_URL: $DUPLICACY_URL" >> "${DEBUG_F}"
  echo "DUPLICACY_UTIL_VERSION: $DUPLICACY_UTIL_VERSION" >> "${DEBUG_F}"
  echo "UTIL_URL: $UTIL_URL" >> "${DEBUG_F}"
fi

wget $DUPLICACY_URL -O /usr/local/bin/duplicacy
wget $UTIL_URL -O /usr/local/bin/duplicacy-util

chmod 755 /usr/local/bin/*
